/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#fad2bf",
        "on-tertiary-fixed": "#341100",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#374c3a",
        "secondary": "#9c4328",
        "error-container": "#ffdad6",
        "surface-container-low": "#fff1eb",
        "surface-variant": "#ffdbcb",
        "on-primary-fixed": "#0c2011",
        "on-secondary-fixed-variant": "#7d2c13",
        "inverse-on-surface": "#ffede6",
        "tertiary-fixed-dim": "#ffb691",
        "inverse-surface": "#432b1e",
        "surface-container": "#ffeae0",
        "secondary-container": "#ff8f6e",
        "on-tertiary-fixed-variant": "#74350d",
        "on-error-container": "#93000a",
        "outline": "#737872",
        "primary-container": "#879e89",
        "on-surface-variant": "#434842",
        "secondary-fixed-dim": "#ffb59f",
        "on-primary-container": "#213525",
        "surface": "#fff8f6",
        "on-error": "#ffffff",
        "inverse-primary": "#b5cdb6",
        "on-secondary-container": "#76270e",
        "on-background": "#2b160b",
        "tertiary": "#914b23",
        "surface-container-highest": "#ffdbcb",
        "tertiary-container": "#d78356",
        "surface-tint": "#4e6451",
        "outline-variant": "#c3c8c0",
        "primary-fixed": "#d0e9d1",
        "on-surface": "#2b160b",
        "primary": "#4e6451",
        "surface-bright": "#fff8f6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b5cdb6",
        "on-secondary": "#ffffff",
        "background": "#fff8f6",
        "secondary-fixed": "#ffdbd1",
        "on-tertiary-container": "#552100",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#3a0a00",
        "surface-container-high": "#ffe2d6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "margin-desktop": "3rem",
        "margin-mobile": "1.25rem",
        "space-xl": "2rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "space-2xs": "0.25rem",
        "space-4xl": "6rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem"
      },
      fontFamily: {
        "headline-hero-mobile": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-md": ["Outfit"],
        "body-lead": ["Outfit"],
        "headline-hero": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "body-sm": ["Outfit"],
        "label-lg": ["Outfit"],
        "quote-poetic": ["Playfair Display"],
        "label-sm": ["Outfit"]
      },
      fontSize: {
        "headline-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "fontWeight": "500" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "38px", "fontWeight": "600" }],
        "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "body-lead": ["19px", { "lineHeight": "30px", "fontWeight": "300" }],
        "headline-hero": ["52px", { "lineHeight": "60px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "quote-poetic": ["20px", { "lineHeight": "32px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}